### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by HePTaset** [stitchEm/stitchEm#101]
Can't help coding-wise as it has been ages since I have done anything.

Still.. I would like to help out - 360° Video professional here so if you need anything testing-wise, or anything else just let me know!

Know my way around FFmpeg and most of the 360° stitching software as well if that would help somehow.

I know this might never come true, but if you lovely contributors and maybe more contributors in the future work on this, maybe even stereo & optical flow could be implemented.. So there might really be an alternative to Mistika..

Anyway, thanks for doing this! Feels so weird being back in VideoStitch after so long, haha.

**Comment by w-m** [comment]
We are badly missing some good documentation for people who have never used the software. There is a GitHub task for it: #85.

You could create a new Markdown document in the doc/ folder on the topic of getting started with the software. And copying the text from the user guide (found as pdf still online on some sites), or writing new text, and filling it with current screen shots.

We also don't have a real product landing page currently. If somebody is interested in a little webdev, a simple product page might make this more accessible. It can even be hosted on GitHub.

Creating and sharing sample projects is also something that would be helpful (see #67).

Or just creating a little more buzz by sharing this project in the appropriate communities! :)
