### ISSUE TITLE
IDEA: Masking to control stitchlines

### ISSUE THREAD

**Issue by HePTaset** [stitchEm/stitchEm#102]
I might have completely missed it, but is there a way to control the stitchlines by masking? That would be an essential feature to get rid of ghosting and optimize the stitch.
Importing masks from PTGui would, of course, also be awesome, just don't know if it is possible at all.

**Comment by w-m** [comment]
There is no UI for masking or editing the control points for calibration directly in VideoStitch Studio. Fine-tuning like that should be done in PTGui.

Masks that mask out parts of the image, like a tripod (negative/red masks?) done in PTGui should apply properly when importing the calibration in VideoStitch Studio. Other types of masks are not supported.

**Comment by HePTaset** [comment]
Can confirm red masks work - makes it possible to create masks for a whole scene, just need to make sure to not rely on green masks.

I'll close this & make sure to implement this information in the documentation.
