### ISSUE TITLE
includes for QPainterPath missing in two files

### ISSUE THREAD

**Issue by frostworx** [stitchEm/stitchEm#117]
both
`src/libvideostitch-gui/widgets/crop/croprectangleeditor.cpp`
and
`src/libvideostitch-gui/widgets/crop/cropcircleeditor.cpp`
are missing a
`#include <QPainterPath>`
include to compile correctly.
using arch **linux** with **qt5-base-5.15.0** here

**Comment by w-m** [comment]
Seems like this header already existed in Qt 5.6, so adding these includes should result in both 5.6 and 5.15 build working correctly. Could you provide a pull request? The source files should already contain a group of other Qt includes, just add this one alphabetically to the group.
