### ISSUE TITLE
Questions about citing articles

### ISSUE THREAD

**Issue by tngh5004** [stitchEm/stitchEm#149]
I want to cite this program in a paper, is it okay to cite this github address or is there a separate address for the paper?
I found a paper with the same name, but I don't think it's about this program.

Thank you for your excellent research.

**Comment by w-m** [comment]
I'm glad you find the work useful. Yes, the GitHub repo address (https://github.com/stitchEm/stitchEm) is the correct way to cite this software in your paper. Appreciate your support!
