### ISSUE TITLE
Limitations in output resolution?

### ISSUE THREAD

**Issue by JochenTCC** [stitchEm/stitchEm#151]
Hi,

I just played around with VideoStitch Studio by "manually" stitching the two raw videos coming from an insta360 X2. Everything worked pretty fine as long as I stayed with the preset output resolution of 2048 to 1024 pixels. But when I try to increase this resolution (because I would like to reframe it afterwards in another tool without losing to much quality) it still processes the input but there is no output file anymore :-(.
So, is there any limitation on the output resolution or is there any possibility to get outputs with better resolution?

**Comment by w-m** [comment]
You can have a look in the processing log for some pointers on what's going wrong.

Most likely you have selected an output resolution > 4K with a h264 codec, which doesn't work (#81).

See https://github.com/stitchEm/stitchEm/issues/27#issuecomment-616196827 and https://github.com/stitchEm/stitchEm/issues/138#issuecomment-804852635 for pointers on how to export higher-resolution outputs.

**Comment by JochenTCC** [comment]
@w-m Thanks for your quick reply. That's it :-)
