### ISSUE TITLE
Support cuda install from package manager

### ISSUE THREAD

**Issue by klem23** [stitchEm/stitchEm#2]
Change our cmake cuda detection file so it can be able to both detect manual cuda installation and cuda installation through package manager.

**Comment by jeremad** [comment]
I think I've done that by accident when adding the CI!

**Comment by klem23** [comment]
an happy accident :joy: 

I check on the ubuntu plugged on my tv, it just need to remove the NO_DEFAULT_PATH for libcudart.
The docker container you use for Travis are from nvidia, and it uses the nvidia install path (/usr/local/cuda), the deb/ubuntu package use the FHS (/usr/include, /usr/lib/x86_64-linux-gnu/). But luckily, the system path are default path for cmake, and they are check after path defined in HINTS (so a manual installed is used over system install when both are there).
Also with system packages, all header are directly in /usr/include/, what a mess.

**Comment by klem23** [comment]
I still have the problem of nvcuvid include before we can compile nvcodec straight on linux.
