### ISSUE TITLE
Original VideoStitch Software

### ISSUE THREAD

**Issue by KaptainKCG** [stitchEm/stitchEm#38]
Hello! I know this is a long shot, but thought I'd ask since it seems the Windows version of this isn't ready yet.
A few years back I purchased a license for VideoStitch Studio V2.  Earlier this year I had to reformat my harddrive, and when I went to reinstall the software the license no longer validated and that's when I learned the company had gone under.
Does anyone know of a way to get my validation code working again? (I still have the original purchase email if needed for verification purposes) 
I just shot a 360 interview a few days ago, and if I can get this working again, it will save me a TON of time.

**Comment by w-m** [comment]
The server that is validating the licenses is no longer running, so software can no longer be registered. You would need to find a backup of your home folder from a time where you had VideoStitch Studio installed and registered, and copy the "videostitch.lic" file over to your current installation to restore the software.

(cc @clairevdv please correct me if I'm wrong)

**Comment by clairevdv** [comment]
That’s correct 😊

**Comment by KaptainKCG** [comment]
Dang... Wish I would have known that a year ago. lol 
I'm searching my backups, but I'm pretty sure I don't have that file.

**Comment by KaptainKCG** [comment]
Good news and Bad news:
Good:  I FOUND THE FILE!! 
Bad:  VideoStitch says "Invalid License Found.  Do you want to activate your product?"
I opened the .Lic file and everything looks accurate.  Version is set to "2.*", my email and name are both correct.  My only guess is the Machine ID is wrong (since I did a full re-install of windows?)
 **"machine_id" : "H+Ab8E+YnpycogDjW1tbW1s=\n",**

**Comment by clairevdv** [comment]
Hi,

Indeed the license file will not work on another PC and a new Windows build is considered as a new PC.

Unfortunately, we haven’t yet compiled the source code without the license system. We plan to do so but have no deadline set.

**Comment by KaptainKCG** [comment]
Damn... Well there's $500+ down the drain.  
Not sure what I'm gonna use for this project instead...

**Comment by w-m** [comment]
Dang that sucks! :(

I don't have any suggestions for your current project. We've made progress over the weekend with the Windows build, please have a look at #16 for announcements on the Windows version from time to time. Hopefully it'll be ready for your next project!

**Comment by w-m** [comment]
The windows version can now be downloaded here: https://github.com/stitchEm/stitchEm/releases/latest
