### ISSUE TITLE
opanAL on MacOS

### ISSUE THREAD

**Issue by aspentreemedia** [stitchEm/stitchEm#45]
I'm running into an issue which appears to be installing openAL on MacOS 10.14.6 (Mojave). When I go through the stitchEm install scripts it's failing on openAL.
>sudo port install opencv glew gsed jpeg libpng openal           tiff faac faad2 ceres-solver glfw ffmpeg glm OpenEXR

--->  Attempting to fetch openal-1.3_0.darwin_18.x86_64.tbz2 from https://packages.macports.org/openal
--->  Attempting to fetch openal-1.3_0.darwin_18.x86_64.tbz2 from http://aus.us.packages.macports.org/macports/packages/openal
--->  Attempting to fetch openal-1.3_0.darwin_18.x86_64.tbz2 from http://ywg.ca.packages.macports.org/mirror/macports/packages/openal
--->  Building openal
Error: Failed to build openal: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_audio_openal/openal/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port openal failed
 Which of course causes issues when I try to cmake.

Looking at main.log as indicated in the terminal error the bit that seems the most relevant is the 404 error:
:debug:archivefetch Fetching archive failed: The requested URL returned error: 404 Not Found
:msg:archivefetch --->  Attempting to fetch openal-1.3_0.darwin_18.x86_64.tbz2 from http://aus.us.packages.macports.org/macports/packages/openal

I'm not familiar enough with where I should be going to get openAL when it fails with macports. I've seen some mention that it's already installed on macOS and I can't find the developer section at creative that appeared to have downloads and openAL.org the SDK download is an .exe

I think Steve in issue #27 ran into the same exact thing I've been facing but I'm not sure how he got openAL installed to finish the cmake.

Any suggestions?

Mike

**Comment by w-m** [comment]
Hi Mike,

just remove `openal` from the install invocation. The package is no longer needed to build the software. It seems there was an oversight in the build documentation when OpenAL support was removed.
