### ISSUE TITLE
igfx_s3dcontrol.h not found error.

### ISSUE THREAD

**Issue by kiokju** [stitchEm/stitchEm#57]
When windows build project, It happen 'igfx_s3dcontrol.h not found error'.

I think it is Intel media SDK version issue.

Is it OK? what version to use??

**Comment by jeremad** [comment]
You need the 2017 version, but it seems it is no longer available on intel's website, I'll check tonight

**Comment by keven-ma** [comment]
Intel_Media_SDK_2017_R1.msi is ok. I download it from 
https://raw.githubusercontent.com/colinporth/d2dWin/master/mfx/Intel_Media_SDK_2017_R1.msi
md5: E59EF9B4565777001D2D9332B49606E0

**Comment by kiokju** [comment]
Thanks!!
