### ISSUE TITLE
Calibration Error

### ISSUE THREAD

**Issue by kiokju** [stitchEm/stitchEm#58]
When Calibration doing on windows10 vs2017 x64 debug build version. 
Error occur at **libstitch-cuda** library and program down.
( rotationDistance.hpp file 20 line  -->  xmemory0 file 880 line (_Ptr is null) )

* input source is magwellpro live cam.
*Is it cuda - version issue?? I used cuda 10.2 version.

**Comment by w-m** [comment]
Do you still get this error when using the official build https://github.com/stitchEm/stitchEm/releases/latest ?

**Comment by w-m** [comment]
This was likely a problem with the CUDA illegal address (#49), should be fixed in the official release.
