### ISSUE TITLE
Exporting with NVENC encoding options crashes Studio

### ISSUE THREAD

**Issue by w-m** [stitchEm/stitchEm#70]
NVENC is not avaiable on Mac, Studio crashes when selecting these. They shouldn't show up where not available.

**Comment by w-m** [comment]
On Linux, where the encoding could potentially work, it also crashes, see report in https://github.com/stitchEm/stitchEm/issues/86#issuecomment-623941296

**Comment by tlalexander** [comment]
I should note that in Linux the crash occurred as soon as I clicked on the NVENC option in the dropdown. Before even trying to export.

**Comment by w-m** [comment]
The NVENC encoding feature was being developed for Vahana VR and doesn't have a UI in Studio yet. It shows up in Studio due to code sharing between Vahana VR and Studio, but it was never working. It will be disabled in the next Studio release (#95).
