### ISSUE TITLE
ccache cache caching

### ISSUE THREAD

**Issue by w-m** [stitchEm/stitchEm#8]
Title says it all?

Travis CI could be sped up by keeping the ccache around between builds: https://docs.travis-ci.com/user/caching/#ccache-cache

Probably needs a little work than this single line to pass it through to the Docker container, but that seems straightforward as well: https://stackoverflow.com/a/39652117/463796

**Comment by jeremad** [comment]
build now takes ~6 minutes on linux (23 minutes before), I'll open the PR, once the BREW PR is merged

**Comment by jeremad** [comment]
On mac ~17 insted of ~32 minutes
