### ISSUE TITLE
Errors importing template from PTGui 10

### ISSUE THREAD

**Issue by elsewhat** [stitchEm/stitchEm#91]
Have extracted stills from VideoStitch to PTGUI 11.27. Added control points and exported to template via "Save as Template ..."

When importing into VideoStitch through Calibration->Import a template->Browse calibration the import fails with "[panorama configuration] invalid configuration Cannot apply the calibration to the current panorama configuration. The calibration has 0 video inputs, the current panorama has 5"
![image](https://user-images.githubusercontent.com/1133607/81477582-d80fb580-9218-11ea-92cd-a6f6daa32108.png)

The main reason this fails is that PTGUI in release 11 (june 2018) has switched to a JSON based format. Here is the PTGUI 11 example file I'm trying to import (had to rename .pts to .txt for github to accept it)
[ptgui11_template.txt](https://github.com/stitchEm/stitchEm/files/4603869/ptgui11_template.txt)

[PTGUI version history](https://www.ptgui.com/versionhistory.html) has the following description: 
"New project file format: Over the years the PTGui .pts project file format has extended upon the original script file format used by Panorama Tools. All the new (and future) changes no longer fit well in this format; therefore PTGui 11 switches to a new JSON based file format. This will make it much easier to incorporate new features in the future. Of course PTGui 11 can read project files from previous versions. Also an 'export to PTGui 10' function is included to enable interoperability with previous versions and third party software, although this will not cover the new functionalities and parameters."

Therefore, exported the template in PTGui 10 format through File->Export->PT GUI 10 project. 
When attempting to importing this in VideoStitch it's at least parsed, but a few errors prevent it from applied. 
First error: "Invalid parameter '0' in panorama line
![image](https://user-images.githubusercontent.com/1133607/81477780-dbf00780-9219-11ea-93cd-23812596714f.png)

This error is thrown from https://github.com/stitchEm/stitchEm/blob/7cf79a5ed0353e4e92109d4ae3a53ead32757339/lib/src/core/defs/ptoParse.cpp#L1019

And as far as I can see it's because of the scientific notation e+0 not being handled
(the code thinks its a new keyword instead of part of the value)
p w2493 h1547 f2 v2.3866944051177779e+02 u0.0000000000000000e+00 n"JPEG g0 q95"

Manually converted the numbers in the text file
(one other instance in addition to the panorama
o w1 h1 y0 r0.0000000000000000e+00 p0.0000000000000000e+00 v1.1611371715017235e+02 a-2.6611977007859056e-02 b9.6513635218542934e-02 c-1.1199153471077572e-01 f0 d1.3578383190335692e+00 e-2.3133098912679517e+00 g0.0000000000000000e+00 t0.0000000000000000e+00)

Here is the PTGUI 10 template file
[pt10_template.txt](https://github.com/stitchEm/stitchEm/files/4603896/pt10_template.txt)
Here is the Videostitch debug log entries:
[videostitch.txt](https://github.com/stitchEm/stitchEm/files/4603904/videostitch.txt)

**Comment by w-m** [comment]
Leaving this ticket for the import problem from the supported PTGui 10 format, created #94 for the feature request of importing PTGui 11 JSON formats.
